config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations], controllers: {sessions: 'admins/sessions'}
  devise_for :users, controllers: {registrations: 'users/registrations'}

  namespace :admin do
    root to: 'home#index'
    resources :admins
    resources :users, only: :index
    resources :posts, only: [:index, :show]
  end

  root to: 'user/timeline#index'

  namespace :user do
    get 'profile', to: 'profile#show'
    get 'potential_to_follow', to: 'profile#potential_to_follow'
    get 'following', to: 'profile#following'
    get 'followers', to: 'profile#followers'
    resources :posts, only: [:create, :destroy] do
      member do 
        post :like_toggle
      end
    end
    resources :users, only: :show
    resources :comments, only: [:create, :destroy]

    post 'follow/:id', to: 'subscriptions#follow', as: :follow
    post 'unfollow/:id', to: 'subscriptions#unfollow', as: :unfollow
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone, :name, :avatar, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar

  has_many :followers_subscriptions, foreign_key: :followed_id, class_name: 'Subscription', dependent: :destroy
  has_many :followers, through: :followers_subscriptions, source: :followed_by, dependent: :destroy

  has_many :following_subscriptions, foreign_key: :followed_by_id, class_name: 'Subscription', dependent: :destroy
  has_many :following, through: :following_subscriptions, source: :followed, dependent: :destroy

  scope :potential_to_follow, -> (user) { where.not(id: user.following.pluck(:id)).where.not(id: user.id) }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
    def index
        @users = User.order(id: :desc)
    end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < UserController

    def create
      f_params = form_params.merge(user: current_user)
      @comment = Comment.new(f_params)
      @post = @comment.post

      if @comment.save
        respond_to do |format|
          format.js { render "create" }
        end
      end
    end

    def destroy
      @comment = Comment.find_by(id: params[:id])
      @post = @comment.post

      if @comment.destroy
        respond_to do |format|
          format.js { render "destroy" }
        end
      end
    end

    private

    def form_params
      params.require(:comment).permit(:body, :post_id)
    end
end

app/controllers/user/posts_controller.rb
class User::PostsController < UserController
    skip_before_action :verify_authenticity_token, only: :like_toggle

    def create
      f_params = form_params.merge(user: current_user)
  
      @post = Post.new(f_params)
      @comment = Comment.new
  
      if @post.save
        redirect_to user_profile_path
      else
        render "user/profile/show"
      end
    end

    def like_toggle
      post = Post.find(params[:id])
      like = Like.find_by(user: current_user, post: post)
      
      if like.present?
        like.destroy
        respond_to {|format| format.json { render json: {liked: false, likesCount: post.likes.count}}}
      else
        Like.create(user:current_user, post: post)
        respond_to {|format| format.json { render json: {liked: true, likesCount: post.likes.count}}}
      end
    end

    def destroy
      @post = current_user.posts.find(params[:id])
      @post.destroy

      redirect_to user_profile_path
    end

    private

    def form_params
      params.require(:post).permit(:body)
    end
end

app/controllers/user/profile_controller.rb
class User::ProfileController < UserController
    def show
        @post = Post.new
        @comment = Comment.new
    end

    def potential_to_follow
        @potential_to_follow = User.potential_to_follow(current_user)
    end

    def following
        @following = current_user.following
    end

    def followers
        @followers = current_user.followers
    end
end

app/controllers/user/subscriptions_controller.rb
class User::SubscriptionsController < UserController

    def follow
        @user_to_follow = User.find_by(id: params[:id])

        Subscription.create(followed_by: current_user, followed: @user_to_follow)

        redirect_to user_potential_to_follow_path
    end

    def unfollow 
        @user = User.find_by(id: params[:id])

        subscription = Subscription.find_by(followed_by: current_user, followed: @user)
        subscription.destroy

        redirect_to user_following_path
    end

end

app/controllers/user/timeline_controller.rb
class User::TimelineController < UserController

    def index
        @posts = Post.where(user_id: current_user.following.pluck(:id)).order(created_at: :desc)
        @comment = Comment.new
    end
end

app/controllers/user/users_controller.rb
class User::UsersController < UserController

    def show
        @user = User.find(params[:id])
        @comment = Comment.new
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :authenticate_user

    def authenticate_user
        redirect_to new_user_session_path unless current_user?
    end

    def current_user?
        current_user.present? ? true : false
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params

    protected

    def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:phone, :name, :avatar])
    end
end

app/views/user/_comment_card.html.erb
<div id='comment<%= comment.id %>'>
 <div class="card text-white bg-dark mb-3 mt-3" style='font-size: 14px;background-color:#464646!important;'>
      <div class="card-header">
      <%= image_tag(comment.user.avatar, class: "ui-w-100-forced rounded-circle mr-2", style: "width: 23px; height: 23px") %>
      <%= link_to comment.user.name, comment.user == current_user ? user_profile_path : user_user_path(comment.user) %>

      <% if comment.user == current_user %>
        <%= link_to user_comment_path(comment), method: :delete, class: 'close text-white', remote: true do %>
            <span aria-hidden="true">&times;</span>
        <% end %>
      <% end %>

      </div>
      <div class="card-body">
        <small class="text-muted"><%= comment.created_at.strftime('%d/%m/%Y %H:%M') %></small>
        <p class="card-text"><%= comment.body %></p>
      </div>
 </div>
</div>

app/views/user/_post_card.html.erb
 <div class="card text-white bg-dark mb-3 mt-3" style='font-size: 17px;'>
      <div class="card-header">
      <%= image_tag(post.user.avatar, class: "ui-w-100-forced rounded-circle mr-2", style: "width: 30px; height: 30px") %>
      <%= link_to post.user.name, post.user == current_user ? user_profile_path : user_user_path(post.user) %>

      <% if post.user == current_user %>
        <%= link_to user_post_path(post), method: :delete, data: {confirm: "Você tem certeza que deseja apagar este post?"}, class: 'close text-white' do %>
            <span aria-hidden="true">&times;</span>
        <% end %>
      <% end %>

      </div>
      <div class="card-body">
        <small class="text-muted"><%= post.created_at.strftime('%d/%m/%Y %H:%M') %></small>
        <p class="card-text"><%= post.body %></p>

        <%= link_to nil, {class: 'like-toggle', id: post.id, remote: true} do %>
          <i style="font-size:18px;color:<%= post.liked_by_user?(current_user) ? "#80c0ff" : "#ffffff" %>" class="fa fa-thumbs-up"></i>
        <% end %>
        <span class="ml-2"><%= post.likes.count %></span>

        <%= link_to nil, {class: 'comments-toggle ml-4', remote: true} do %>
          <i style="font-size:18px;color: white" class="fa fa-comment"></i>
        <% end %>
        <span class="ml-2" id="post<%= post.id %>-comments-count"><%= post.comments.count %></span>
      </div>
    </div>

<div class='comments-list' style='display: none;'>
  <%= form_with(model: [:user, @comment], local: false) do |f| %>
    <%= f.hidden_field(:post_id, value: post.id) %>
    <div class="form-group">
      <%= f.text_area :body, rows: 2, class: 'form-control', placeholder: "Escreva seu comentário...", required: true %>
    </div>
    <div class="d-flex">
      <button type="submit" class="btn btn-sm btn-primary ml-auto">Enviar</button>
    </div>
  <% end %>
  
  <div id='post<%= post.id %>-comments'>
    <% post.comments.order(created_at: :desc).each do |comment| %>
      <%= render 'comment_card', comment: comment %>
    <% end %>
  </div>
</div>

<hr class='bg-secondary'>

app/views/user/_user_card_header.html.erb
<h5 class="card-header">
    <td><%= image_tag(user.avatar, class: "ui-w-100-forced rounded-circle mr-2", style: "width: 90px; height: 90px") %></td>
    <%= link_to user.name, user == current_user ? user_profile_path : user_user_path(user) %>
    <br/>
    <span style="font-size:14px;">Seguidores:</span> <span style="font-size:16px;" class="badge badge-info mr-3"><%= user.followers.count %></span>
    <span style="font-size:14px;">Seguindo:</span> <span style="font-size:16px;" class="badge badge-info"><%= user.following.count %></span>
</h5>