config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations], controllers: {sessions: 'admins/sessions'}
  devise_for :users, controllers: {registrations: 'users/registrations'}

  namespace :admin do
    root to: 'home#index'
    resources :admins
    resources :users, only: :index
    resources :posts, only: [:index, :show]
  end

  root to: 'user/timeline#index'

  namespace :user do
    get 'profile', to: 'profile#show'
    get 'potential_to_follow', to: 'profile#potential_to_follow'
    get 'following', to: 'profile#following'
    get 'followers', to: 'profile#followers'
    resources :posts, only: [:create, :destroy] do
      member do 
        post :like_toggle
      end
    end
    resources :users, only: :show
    resources :comments, only: [:create, :destroy]

    post 'follow/:id', to: 'subscriptions#follow', as: :follow
    post 'unfollow/:id', to: 'subscriptions#unfollow', as: :unfollow
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone, :name, :avatar, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar

  has_many :followers_subscriptions, foreign_key: :followed_id, class_name: 'Subscription', dependent: :destroy
  has_many :followers, through: :followers_subscriptions, source: :followed_by, dependent: :destroy

  has_many :following_subscriptions, foreign_key: :followed_by_id, class_name: 'Subscription', dependent: :destroy
  has_many :following, through: :following_subscriptions, source: :followed, dependent: :destroy

  scope :potential_to_follow, -> (user) { where.not(id: user.following.pluck(:id)).where.not(id: user.id) }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
    def index
        @users = User.order(id: :desc)
    end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < UserController

    def create
      f_params = form_params.merge(user: current_user)
      @comment = Comment.new(f_params)
      @post = @comment.post

      if @comment.save
        respond_to do |format|
          format.js { render "create" }
        end
      end
    end

    def destroy
      @comment = Comment.find_by(id: params[:id])
      @post = @comment.post

      if @comment.destroy
        respond_to do |format|
          format.js { render "destroy" }
        end
      end
    end

    private

    def form_params
      params.require(:comment).permit(:body, :post_id)
    end
end

app/controllers/user/posts_controller.rb
class User::PostsController < UserController
    skip_before_action :verify_authenticity_token, only: :like_toggle

    def create
      f_params = form_params.merge(user: current_user)
  
      @post = Post.new(f_params)
      @comment = Comment.new
  
      if @post.save
        redirect_to user_profile_path
      else
        render "user/profile/show"
      end
    end

    def like_toggle
      post = Post.find(params[:id])
      like = Like.find_by(user: current_user, post: post)
      
      if like.present?
        like.destroy
        respond_to {|format| format.json { render json: {liked: false, likesCount: post.likes.count}}}
      else
        Like.create(user:current_user, post: post)
        respond_to {|format| format.json { render json: {liked: true, likesCount: post.likes.count}}}
      end
    end

    def destroy
      @post = current_user.posts.find(params[:id])
      @post.destroy

      redirect_to user_profile_path
    end

    private

    def form_params
      params.require(:post).permit(:body)
    end
end

app/controllers/user/profile_controller.rb
class User::ProfileController < UserController
    def show
        @post = Post.new
        @comment = Comment.new
    end

    def potential_to_follow
        @potential_to_follow = User.potential_to_follow(current_user)
    end

    def following
        @following = current_user.following
    end

    def followers
        @followers = current_user.followers
    end
end

app/controllers/user/subscriptions_controller.rb
class User::SubscriptionsController < UserController

    def follow
        @user_to_follow = User.find_by(id: params[:id])

        Subscription.create(followed_by: current_user, followed: @user_to_follow)

        redirect_to user_potential_to_follow_path
    end

    def unfollow 
        @user = User.find_by(id: params[:id])

        subscription = Subscription.find_by(followed_by: current_user, followed: @user)
        subscription.destroy

        redirect_to user_following_path
    end

end

app/controllers/user/timeline_controller.rb
class User::TimelineController < UserController

    def index
        @posts = Post.where(user_id: current_user.following.pluck(:id)).order(created_at: :desc)
        @comment = Comment.new
    end
end

app/controllers/user/users_controller.rb
class User::UsersController < UserController

    def show
        @user = User.find(params[:id])
        @comment = Comment.new
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :authenticate_user

    def authenticate_user
        redirect_to new_user_session_path unless current_user?
    end

    def current_user?
        current_user.present? ? true : false
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params

    protected

    def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:phone, :name, :avatar])
    end
end

app/views/layouts/user/_header.html.erb
<nav class="navbar navbar-expand-sm bg-primary navbar-dark" style="background-color:#000080!important;">
  <div class="container" >
    <%= image_tag("logo.png", alt: "logo", class: 'navbar-brand', style: "height:40px;")%>
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(root_path)? "active" : "" %>">
        <a class="nav-link" href="<%= root_path %>">Timeline</a>
      </li>
      <li class="nav-item <%= current_page?(user_followers_path)? "active" : "" %>">
        <a class="nav-link" href="<%= user_followers_path %>">Followers</a>
      </li>
      <li class="nav-item <%= current_page?(user_following_path)? "active" : "" %>">
        <a class="nav-link" href="<%= user_following_path %>">Following</a>
      </li>
      <li class="nav-item <%= current_page?(user_potential_to_follow_path)? "active" : "" %>">
        <a class="nav-link" href="<%= user_potential_to_follow_path %>">Quem eu posso seguir</a>
      </li>
      <li class="nav-item <%= current_page?(user_profile_path)? "active" : "" %>">
        <a class="nav-link" href="<%= user_profile_path %>">Meu Perfil</a>
      </li>
    </ul>
    <div class="nav-item d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="py-2 mr-4" style="color:#fff;"><%= current_user.email %></div>
        </li>
        <li class="nav-item">
          <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>